### ISSUE TITLE
与function calling 结合的示例

### ISSUE THREAD

**Issue by rxdaozhang** [EmbraceAGI/LangGPT#10]
请问是否可以加入与openai function calling结合的示例？感觉openai后面是把function calling结构化后拼接在prompt后执行的，但是不知道具体逻辑。在使用fuction calling时如何把对tool使用的指导更好的写进结构化prompt里？

**Comment by yzfly** [comment]
对 tool 的使用一直在计划中，但是本人时间精力有限，所以鸽了很久其实，，，你有好的实验结论欢迎贡献~
