### ISSUE TITLE
prompt 中英文混用的效果好嗎？

### ISSUE THREAD

**Issue by easontsai** [EmbraceAGI/LangGPT#12]
如果我面向的使用者都是中文使用者，問的問題也都是中文為主

這樣的話prompt的設計要以中文為主嗎？還是其實無所謂。

順帶一問，對於GPT4的prompt 消耗的token量過大，有辦法精簡prompt又維持一樣的prompt品質嗎？

**Comment by yzfly** [comment]
1. 中英文无所谓
2. token 消耗量由任务复杂度决定，模板中的模块可增删改自由调整，并不会带来显著 token 增加
3. 提示词编写到一定水平后，建议抛开模板，关键在于融汇贯通
