### ISSUE TITLE
Why are the LangGPT Helper prompts so different for GPT-3.5 vs GPT-4?

### ISSUE THREAD

**Issue by galantra** [EmbraceAGI/LangGPT#9]
The most obvious difference being that the GPT-4 one is much longer.

Reference: https://github.com/yzfly/LangGPT/tree/0ed0c5360388f352c6dbf80b8d7ce738d3669d28/LangGPT

**Comment by yzfly** [comment]
No particular reason, any format is fine, the key is the idea of writing Prompts in a modular structured style. The GPT-4 prompts are longer because of we want to fully utilize the capabilities of the GPT-4, to explore it's power limitation.
